In [2]:
import numpy as np

In [2]:
x = np.array([1,0,1,0])

In [3]:
x[0]=~x[0]

In [4]:
x[0]

-2

In [20]:
y = np.array([1,0,1,0])

In [11]:
y[0]=~y[0]

In [12]:
y[0]

-2

In [13]:
y[0] &= y[0] - 1
y[0]

-4

In [18]:
y = np.array([1,0,1,0])

In [19]:
y[0]=np.invert(np.array(y[0]))
y    

array([-2,  0,  1,  0])

In [25]:
y = np.array([1,0,1,0])

In [28]:
indice=3

if y[indice]==0:
    y[indice]=1
else:
    y[indice]=0

In [29]:
y

array([0, 0, 1, 1])

In [46]:
x = np.array([[4,10,20,45],
            [8,12,15,26],
            [33,24,16,20]])

In [47]:
x

array([[ 4, 10, 20, 45],
       [ 8, 12, 15, 26],
       [33, 24, 16, 20]])

In [48]:
x[0]

array([ 4, 10, 20, 45])

In [49]:
x[0:]

array([[ 4, 10, 20, 45],
       [ 8, 12, 15, 26],
       [33, 24, 16, 20]])

In [50]:
x[0,:]

array([ 4, 10, 20, 45])

In [51]:
b = np.array([[1,0,1,0],
             [1,0,1,0],
             [1,0,1,0],
             [1,0,1,0]])

In [52]:
c=np.dot(x,b)
c

array([[79,  0, 79,  0],
       [61,  0, 61,  0],
       [93,  0, 93,  0]])

In [53]:
x

array([[ 4, 10, 20, 45],
       [ 8, 12, 15, 26],
       [33, 24, 16, 20]])

In [54]:
b

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 0, 1, 0]])

In [58]:
x = np.array([[4,10,20],
            [8,12,15],
            [33,24,16]])

In [61]:
b = np.array([[1,0,1],
             [1,0,1],
             [1,0,1]])

In [63]:
c=x*b
c

array([[ 4,  0, 20],
       [ 8,  0, 15],
       [33,  0, 16]])

In [64]:
b = np.array([1,0,1])
c=x*b
c

array([[ 4,  0, 20],
       [ 8,  0, 15],
       [33,  0, 16]])

In [70]:
#find zero values
x = np.array([1,0,2,0,3,0,4,5,6,7,8])
indices=np.where(x == 0)[0]
indices

array([1, 3, 5])

In [71]:
y=np.array([[ 4,  0, 20],
       [ 8,  0, 15],
       [33,  0, 16]])

In [73]:
indices=np.where(y[0] == 0)
indices

(array([1]),)

In [77]:
b=np.delete(y,indices,axis=1)
b

array([[ 4, 20],
       [ 8, 15],
       [33, 16]])

In [78]:
y

array([[ 4,  0, 20],
       [ 8,  0, 15],
       [33,  0, 16]])